---
- name: Install Dependencies
  hosts: worknodes
  become: true
  vars: 
  tasks:
    - name: Update Repository
      command: sudo apt-update

    - name: Check if Git is installed
      command: git --version
      register: git_check
      ignore_errors: yes
    - name: Check if Maven is installed
      command: mvn --version
      register: maven_check
      ignore_errors: yes
    - name: Check if Docker is installed
      command: docker --version
      register: docker_check
      ignore_errors: yes
    
    
    - name: Install Docker
      package:
        name: docker-ce
        state: present
      when: docker_check.rc != 0

    - name: Install Git
      package:
        name: git
        state: present
      when: git_check.rc != 0

    - name: Install Maven
      package:
        name: maven
        state: present
      when: maven_check.rc != 0
