---
- name: Install Dependencies
  hosts: worknodes
  become: true
  vars: 
  tasks:
    - name: Update Repository
      command: sudo apt-get update

    - name: Check if Git is installed
      command: git --version
      register: git_check
      ignore_errors: yes
    - name: Check if Maven is installed
      command: mvn --version
      register: maven_check
      ignore_errors: yes

    - name: Install Git
      package:
        name: git
        state: present
      when: git_check.rc != 0

    - name: Install Maven
      package:
        name: maven
        state: present
      when: maven_check.rc != 0

    - name: Clone the repository
      git: repo=https://github.com/Sonal0409/DevOpsCodeDemo.git dest=/tmp/code

    - name: Build with Maven
      command: chdir=/tmp/code mvn package
    
